apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  mtls:
    enabled: true
  tracing:
    samplingRate: "1"
  metrics:
    enabled: true
    port: "9090"
