version: '3.8'

services:
  # user service - MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user_service
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservicesproject_mynetwork


volumes:
  mongodb_data:

networks:
  microservicesproject_mynetwork:
    external: true

#
#services:
#  ########################
#  # MongoDB Service
#  ########################
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb-user
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
#      - MONGO_INITDB_DATABASE=user_service
#    volumes:
#      - mongodb_data:/data/db
#    networks:
#      - microservicesproject_mynetwork
#
#  ########################
#  # Spring Boot App Service
#  ########################
#  user-service:
#    build:
#      context: ./user-service
#      dockerfile: Dockerfile
#    container_name: user-service
#    ports:
#      - 8081:8080
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb-user:27017/user_service?authSource=admin
#    depends_on:
#      - mongodb
#    networks:
#      - microservicesproject_mynetwork
#
#  ########################
#  # Dapr Sidecar for Spring Boot App
#  ########################
#  user-service-dapr:
#    image: "daprio/daprd:edge"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 10
#        window: 120s
#    command: ["./daprd",
#              "-app-id", "user-service",
#              "-app-port", "8080",
#              "-app-protocol", "http",
#              "-dapr-http-port", "3500",
#              "-resources-path", "./dapr/components",
#              "-config", "./dapr/config.yaml"
#    ]
#    volumes:
#      - "./dapr/:/dapr"
#    depends_on:
#      - user-service
#    networks:
#      - microservicesproject_mynetwork
#    ports:
#      - 3500:3500
#
#volumes:
#  mongodb_data:
#
#networks:
#  microservicesproject_mynetwork:
#    external: true




#services:
#  ########################
#  # MongoDB Service
#  ########################
#  mymongodb:
#    image: mongo:latest
#    container_name: mymongodb
#    ports:
#      - 27017:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
#      - MONGO_INITDB_DATABASE=user_service
#    volumes:
#      - ./mongo-data:/data/db
#    networks:
#      - microservicesproject_mynetwork
#
#  ########################
#  # Spring Boot App Service
#  ########################
#  springboot-mongodb:
#    build:
#      context: ./user-service
#      dockerfile: Dockerfile
#    container_name: springboot-mongodb
#    ports:
#      - 8081:8080
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mymongodb:27017/user_service?authSource=admin
#    depends_on:
#      - mymongodb
#    networks:
#      - microservicesproject_mynetwork
#
#  ########################
#  # Dapr Sidecar for Spring Boot App
#  ########################
#  springboot-mongodb-dapr:
#    image: "daprio/daprd:edge"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 10
#        window: 120s
#    command: ["./daprd",
#              "-app-port", "8080",
#              "-app-id", "springboot-mongodb",
#              "-app-protocol", "http",
#              "-dapr-http-port", "3500",
#              "-resources-path", "./dapr/components",
#              "-config", "./dapr/config.yaml"
#    ]
#    volumes:
#      - "./dapr/:/dapr"
#    depends_on:
#      - springboot-mongodb
#    networks:
#      - microservicesproject_mynetwork
#    ports:
#      - 3500:3500
#
#networks:
#  microservicesproject_mynetwork:
#    external: true
